server:
  port: 11001

spring:
  profiles:
    active: dev
  application:
    name: onlinebiz-contract
  data:
    mongodb:
      host: 124.221.156.98
      username: root
      password: nAnj1ng_Jia0tong_Univ
      database: onlinebiz
      authentication-database: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

eureka:
  instance:
    instance-id: contract-service11001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
