server:
  port: 8080

spring:
  application:
    name: onlinebiz-gateway
  cloud:
    gateway:
      # 使用DiscoveryClient
      discovery:
        locator:
          enabled: true
      # 配置网关路由
      routes:
        - id: user-service-public
          uri: lb://onlinebiz-user
          predicates:
            - name: Path
              args:
                patterns:
                  - /login/**
                  - /logout
                  - /register
                  - /account/username
                  - /account/password
                  - /account
                  - /account/search
                  - /user/{userId}

        - id: user-service-private
          uri: lb://onlinebiz-user
          predicates:
            - name: Path
              args:
                patterns:
                  - /account/role
          filters:
            - AddIdentity

eureka:
  instance:
    instance-id: gateway8080
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
