server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: onlinebiz-gateway
  redis:
    host: 124.221.156.98
    database: 0
    password: nAnj1ng_Jia0tong_Univ
  cloud:
    gateway:
      # 使用DiscoveryClient
      discovery:
        locator:
          enabled: true
      # 配置网关路由
      routes:
        - id: user-service-public
          uri: lb://onlinebiz-user
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/login
                  - /api/logout
                  - /api/register
                  - /api/account/username
                  - /api/account/password
                  - /api/account
                  - /api/user/search
                  - /api/user/{userId}

        - id: user-service-private
          uri: lb://onlinebiz-user
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/account/role
          filters:
            - AddIdentity

        - id: entrust-service
          uri: lb://onlinebiz-entrust
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/entrust/**
          filters:
            - AddIdentity

        - id: contract-service
          uri: lb://onlinebiz-contract
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/contract/**
          filters:
            - AddIdentity

eureka:
  instance:
    instance-id: gateway8080
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
