spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://128.199.174.49:3306/UserDB
    username: root
    password: nAnj1ng_Jia0tong_Univ
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,,*.jpg,*.png,*.css,*.ico,/druid/*'

      aop-patterns: com.example.demo.*
      filters: stat,wall,slf4j
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      max-active:
        10

server:
  port: 8001
