spring:
  application:
    name: onlinebiz-user
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: test_user
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 30m

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.njustc.onlinebiz.user.model
  configuration:
    jdbc-type-for-null: null
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

server:
  port: 8001
  servlet:
    session:
      timeout: 7d
      cookie:
        name: NJUSTC_ONLINEBIZ_SESSION
        max-age: 7d
        path: /
        http-only: true
