server:
  port: 9001

spring:
  application:
<<<<<<<< HEAD:onlinebiz-test/src/main/resources/application-dev.yml
    name: onlinebiz-test
========
    name: onlinebiz-entrust
>>>>>>>> dev:onlinebiz-entrust/src/main/resources/application-dev.yml
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: nAnj1ng_Jia0tong_Univ
      database: onlinebiz
      authentication-database: admin

eureka:
  instance:
<<<<<<<< HEAD:onlinebiz-test/src/main/resources/application-dev.yml
    instance-id: test-service9001
========
    instance-id: entrust-service10001
>>>>>>>> dev:onlinebiz-entrust/src/main/resources/application-dev.yml
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
